CREATE TABLE IF NOT EXISTS students
(
    student_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_name     VARCHAR(250)                            NOT NULL,
    students_surname VARCHAR(250)                            NOT NULL,
    date_of_birth    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sex              VARCHAR(6)                              NOT NULL,
    email            VARCHAR(50) UNIQUE                      NOT NULL,
    student_rate     SERIAL,

    CONSTRAINT pk_students PRIMARY KEY (student_id)

);

CREATE TABLE IF NOT EXISTS subjects
(
    subject_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_name      VARCHAR(250)                            NOT NULL,
    description       VARCHAR(2000)                           NOT NULL,
    start_course_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_course_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    students_count    BIGINT,
    CONSTRAINT pk_subjects PRIMARY KEY (subject_id)
);

CREATE TABLE IF NOT EXISTS grades
(
    grade_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT                                  NOT NULL,
    subject_id BIGINT                                  NOT NULL,
    grade      SMALLINT                                NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    FOREIGN KEY (student_id)
        REFERENCES students (student_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id)
        REFERENCES subjects (subject_id) ON DELETE CASCADE,
    CONSTRAINT pk_grades PRIMARY KEY (grade_id)
);

